/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GJD_About.java
 *
 * Created on 2012-1-15, 14:01:03
 */
package jappm.ui;

import jappm.Common;

/**
 *
 * @author Ivan
 */
public class GJD_About extends javax.swing.JDialog {

    /** Creates new form GJD_About */
    public GJD_About(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.jLabel1.setIcon(Common.getImageAsIconWithSize(((JF_MainW) parent).ABOUT_IMAGE,
                this.jLabel1.getWidth(), this.jLabel1.getHeight()));
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        setModal(true);
        setResizable(false);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("This is a free Java-based email client with \nPOP3 and IMAP support.\nName: JAPP Mail (Java All Platforms Portable Mail)\nAuthor: Ivan Georgiev\nFor contact: jappmail.bg@gmail.com\nYear: 2012\nVersion: 1.0\n\nImages in the application are from:\nhttp://us.fotolia.com\nhttp://www.softicons.com\nhttp://www.iconfinder.com\nhttp://www.shutterstock.com\n");
        jTextArea1.setCaretPosition(0);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
